# Generated by Django 5.0.6 on 2024-05-15 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
    ]
